#!/bin/bash

# Phase 1: Simple Test - Create test-{vegetable}.js files with Copilot CLI
# This verifies that the Copilot CLI works with all models before running the full spec

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASSIGNMENT_FILE="$SCRIPT_DIR/vegetable-assignment.json"
TIMING_FILE="$SCRIPT_DIR/timing-data.json"
TEST_DIR="$SCRIPT_DIR/phase1-results"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Phase 1: Simple Copilot CLI Test${NC}"
echo -e "${BLUE}========================================${NC}"

# Check if assignment file exists
if [ ! -f "$ASSIGNMENT_FILE" ]; then
  echo -e "${RED}❌ No vegetable assignment file found!${NC}"
  echo -e "${YELLOW}Run: node testing/assign-vegetables.js${NC}"
  exit 1
fi

# Create test results directory
mkdir -p "$TEST_DIR"

# Get current branch
ORIGINAL_BRANCH=$(git branch --show-current)
echo -e "${BLUE}📍 Current branch: $ORIGINAL_BRANCH${NC}"

# Parse assignments and test each model
echo -e "\n${BLUE}🚀 Starting model tests...${NC}\n"

# Read the assignment file and extract model names (one per line)
# Use process substitution to avoid subshell issues
while IFS= read -r MODEL_NAME; do
  echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}Testing: $MODEL_NAME${NC}"
  echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

  # Get vegetable name for this model
  VEGETABLE=$(node -p "require('$ASSIGNMENT_FILE')['$MODEL_NAME'].vegetable")
  BRANCH_NAME="test/model-$(echo $VEGETABLE | tr '[:upper:]' '[:lower:]')"

  echo -e "${BLUE}🥬 Vegetable: $VEGETABLE${NC}"
  echo -e "${BLUE}🌿 Branch: $BRANCH_NAME${NC}"

  # Create and checkout branch
  git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

  # Determine model identifier for copilot CLI
  case "$MODEL_NAME" in
    "Sonnet 4.5")
      MODEL_ID="claude-sonnet-4.5"
      ;;
    "Opus 4.5")
      MODEL_ID="claude-opus-4.5"
      ;;
    "Codex 5.2")
      MODEL_ID="gpt-5.2-codex"
      ;;
    "Codex 5.1 Max")
      MODEL_ID="gpt-5.1-codex-max"
      ;;
    "Gemini 3 Pro")
      MODEL_ID="gemini-3-pro-preview"
      ;;
    "Gemini 3 Flash")
      MODEL_ID="gemini-3-flash-preview"
      ;;
    "DeepSeek")
      MODEL_ID="deepseek"
      ;;
    *)
      echo -e "${RED}❌ Unknown model: $MODEL_NAME${NC}"
      continue
      ;;
  esac

  echo -e "${BLUE}🤖 Model ID: $MODEL_ID${NC}"

  # Create prompt
  PROMPT="create file testing/phase1-results/test-${VEGETABLE}.js with a simple function that calculates factorial of a number, add JSDoc comments, do not ask any questions"

  # Run copilot CLI and capture output
  echo -e "${YELLOW}⏳ Running Copilot CLI...${NC}"
  START_TIME=$(date +%s)

  OUTPUT_FILE="$TEST_DIR/output-${VEGETABLE}.txt"

  copilot -p "$PROMPT" --allow-all-tools --allow-all-paths --model "$MODEL_ID" 2>&1 | tee "$OUTPUT_FILE"

  END_TIME=$(date +%s)
  DURATION=$((END_TIME - START_TIME))

  # Extract timing from copilot output (look for "Total session time")
  SESSION_TIME=$(grep "Total session time:" "$OUTPUT_FILE" | awk '{print $4}' || echo "${DURATION}s")

  echo -e "${GREEN}✅ Completed in: $SESSION_TIME${NC}"

  # Verify file was created
  if [ -f "$TEST_DIR/test-${VEGETABLE}.js" ]; then
    echo -e "${GREEN}✅ File created: test-${VEGETABLE}.js${NC}"

    # Add and commit
    git add "$TEST_DIR/test-${VEGETABLE}.js"
    git add "$OUTPUT_FILE"
    git commit -m "Phase 1: Add test file for $VEGETABLE (model: $MODEL_NAME)

Generated by Copilot CLI with model: $MODEL_ID
Session time: $SESSION_TIME

Co-Authored-By: AI Agent <noreply@copilot.com>"

    echo -e "${GREEN}✅ Committed changes${NC}"
  else
    echo -e "${RED}❌ File not created!${NC}"
  fi

  # Checkout main and merge
  git checkout "$ORIGINAL_BRANCH"
  git merge "$BRANCH_NAME" --no-edit
  echo -e "${GREEN}✅ Merged to $ORIGINAL_BRANCH${NC}"

  # Update timing data
  node -e "
    const fs = require('fs');
    const data = require('$TIMING_FILE');
    const model = data.models.find(m => m.model === '$MODEL_NAME');
    if (model) {
      const time = '$SESSION_TIME'.replace('s', '');
      model.durationSeconds = parseInt(time) || $DURATION;
      model.durationMinutes = Math.floor(model.durationSeconds / 60);
      model.durationSeconds = model.durationSeconds % 60;
      fs.writeFileSync('$TIMING_FILE', JSON.stringify(data, null, 2));
    }
  "

  echo -e "${GREEN}✅ Updated timing data${NC}"
  echo ""
done < <(node -p "Object.keys(require('$ASSIGNMENT_FILE')).join('\n')")

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}✨ Phase 1 Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "${YELLOW}📊 Results saved in: $TEST_DIR${NC}"
echo -e "${YELLOW}⏱️  Timing data updated in: $TIMING_FILE${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo -e "  1. Review test files in $TEST_DIR"
echo -e "  2. Run ${YELLOW}pnpm run build${NC} to verify"
echo -e "  3. If all looks good, proceed to Phase 2"
echo ""
